id: I04985E0C
ocr_import_info:
  timestamp: '2023-06-19T04:28:01.858373+00:00'
  batch_id: batch-4b35
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Peche job
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-19 04:51:41.351314+00:00
last_modified: 2023-06-19 04:51:41.351320+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23576
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23576
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨོ་རྒྱན་ཞལ་གདམས་སྙིང་ཐུར།
  languages:
  - bo
  author: གཏེར་སྟོན་སངས་རྒྱས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9786538561540288
  ocr_word_median_confidence_index: 0.9998411
bases:
  I1KG5186:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5186
      total_pages: 100
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5186.txt
    statistics:
      ocr_word_median_confidence_index: 0.9998411
      ocr_word_mean_confidence_index: 0.9786538561540288
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
